### ISSUE TITLE
Conv2DCustomBackpropInputOp only supports NHWC

### ISSUE THREAD

**Issue by vlad-i** [YotamNitzan/ID-disentanglement#2]
Hello and thanks for publishing this nice repo!

I've tried running test.py after following the setup instructions and am getting an error, not sure how to solve this

`python test.py  Whut --pretrained_models_path ./modele/stylegan_G_256x256/  --gpu 0   --load_checkpoint ./checkpointuri/checkpoint/ --resolution 256      --input_dir ./imagini/     --output_dir ./rezultate/     --test_func interpolate  `

```
Traceback (most recent call last):
  File "test.py", line 45, in <module>
    main()
  File "test.py", line 41, in main
    test_func()
  File "/home/ubuntu/gituri/ID-disentanglement/inference.py", line 115, in interpolate
    const_img = self.G(const_img, const_img)[0]
  File "/home/ubuntu/anaconda3/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/ubuntu/anaconda3/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 526, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/ubuntu/anaconda3/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/home/ubuntu/anaconda3/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/ubuntu/anaconda3/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/ubuntu/anaconda3/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Conv2DCustomBackpropInputOp only supports NHWC.
         [[node G_synthesis/G_synthesis/128x128/Conv0_up/conv2d_transpose (defined at /home/ubuntu/anaconda3/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_call_25996]

Function call stack:
call

```

If I try changing from NCHW to NHWC then some dimensions stop working. I've also tried passing it the --gpu 0 and --gpu 1 parameters but that doesn't have an effect.

Is there something I am missing? Is this maybe familiar to you?

Thanks

**Comment by beyondendless** [comment]
I meet a question same as you,I run main.py 

python main.py NAME --resolution 256 --pretrained_models_path /opt/data/private/sunky/ID-disentanglement-main/pretrained/ --dataset /opt/data/private/sunky/ID-disentanglement-main/output/ --batch_size 50 --cross_frequency 3 --train_data_size 70000 --results_dir /opt/data/private/sunky/ID-disentanglement-main/result/

Traceback (most recent call last):
  File "main.py", line 98, in <module>
    main()
  File "main.py", line 94, in main
    trainer.train()
  File "/opt/data/private/sunky/ID-disentanglement-main/trainer.py", line 81, in train
    self.test()
  File "/opt/data/private/sunky/ID-disentanglement-main/trainer.py", line 283, in test
    pred, id_embedding, w, attr_embedding, src_lnds = self.model.G(id_img, attr_img)
  File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 526, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node attr_encoder/StatefulPartitionedCall/inception_v3/conv2d/Conv2D}}]] [Op:__inference_call_87125]

I think there is something wrong with environment,but I don't know how to solve it,do you have some ideas?

**Comment by beyondendless** [comment]
I meet a question same as you,I run main.py

`python main.py NAME --resolution 256 --pretrained_models_path /opt/data/private/sunky/ID-disentanglement-main/pretrained/ --dataset /opt/data/private/sunky/ID-disentanglement-main/output/ --batch_size 50 --cross_frequency 3 --train_data_size 70000 --results_dir /opt/data/private/sunky/ID-disentanglement-main/result/`

> Traceback (most recent call last):
File "main.py", line 98, in
main()
File "main.py", line 94, in main
trainer.train()
File "/opt/data/private/sunky/ID-disentanglement-main/trainer.py", line 81, in train
self.test()
File "/opt/data/private/sunky/ID-disentanglement-main/trainer.py", line 283, in test
pred, id_embedding, w, attr_embedding, src_lnds = self.model.G(id_img, attr_img)
File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in call
outputs = self.call(cast_inputs, *args, **kwargs)
File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in call
result = self._call(*args, **kwds)
File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 526, in _call
return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds) # pylint: disable=protected-access
File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
self.captured_inputs)
File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
ctx, args, cancellation_manager=cancellation_manager)
File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
ctx=ctx)
File "/root/anaconda2/envs/id_disen/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
six.raise_from(core._status_to_exception(e.code, message), None)
File "", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
[[{{node attr_encoder/StatefulPartitionedCall/inception_v3/conv2d/Conv2D}}]] [Op:__inference_call_87125]

I think there is something wrong with environment,but I don't know how to solve it,do you have some ideas?

**Comment by NTU-P04922004** [comment]
This seems like a TensorFlow environment issue. Maybe you can check if a simple TensorFlow program can be run on your machine first. I have encountered the ```Conv2DCustomBackpropInputOp only supports NHWC``` issue, and the CUDA version does not match with the prebuilt TensorFlow. The issue is solved by setting up the correct version of CUDA with the installed TensorFlow.

You can check your CUDA version and the installed TensorFlow version with the official document here:
[https://www.tensorflow.org/install/source#gpu](https://www.tensorflow.org/install/source#gpu)

**Comment by YotamNitzan** [comment]
Hi,

I agree with @NTU-P04922004. This is usually a compatibility issue between TF and CUDA versions.
I've uploaded the environment file I've used which is supposed to be compatible with CUDA 10.1. If you are using a different CUDA version please make sure you are using an appropriate version of TF.
