### ISSUE TITLE
Loading pretrained StyleGAN weights (h5)

### ISSUE THREAD

**Issue by NTU-P04922004** [YotamNitzan/ID-disentanglement#7]
I have encountered an issue when generating the training dataset.

I ran the ```generate_fake_data.py``` script but it failed with the following error:

```shell
Model created.                                                                                                                             
Traceback (most recent call last):                                                                                                   
  File "generate_fake_data.py", line 91, in <module>                                                                            
    main(args)                                                                                                                      
  File "generate_fake_data.py", line 44, in main                                                                                   
    stylegan_G.load_weights(str(stylegan_G_path))                                                                                   
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 2200, in load_weights                       
    'Unable to load weights saved in HDF5 format into a subclassed '                                                                     
ValueError: Unable to load weights saved in HDF5 format into a subclassed Model which has not created its variables yet. Call the Model first
, then load the weights.      
```
PS:
My development environment is ```TensorFlow``` v2.3 and the pretrained weight I use is ```FFHQ StyleGAN 256x256``` from the [setup](https://github.com/YotamNitzan/ID-disentanglement/blob/main/docs/setup.md) doc.

Any idea what has caused this issue?

**Comment by NTU-P04922004** [comment]
It turns out that I should run one time inference before loading ```.h5``` model weights.

Just add one line prediction code before the ```load_weights``` method:
```python
stylegan_G(tf.ones((1, 512)))
```

Reference:
[Tensorflow 2.0 ValueError while Loading weights from .h5 file](https://stackoverflow.com/a/64687235)
