### ISSUE TITLE
Generate 256x256 size training data

### ISSUE THREAD

**Issue by NTU-P04922004** [YotamNitzan/ID-disentanglement#8]
I have encountered an issue when generating 256x256 training dataset.
However, I can generate 1024x1024 training data without any error.

The generate_fake_data.py script failed with the following error message:

```shell
Traceback (most recent call last):
  File "generate_fake_data.py", line 85, in <module>
    main(args)
  File "generate_fake_data.py", line 37, in main
    stylegan_G(tf.ones((1, 512)))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "../model/stylegan.py", line 483, in call
    x = self.model_synthesis(x)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 998, in __call__
    input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/input_spec.py", line 274, in assert_input_compatibility
    ', found shape=' + display_shape(x.shape))
ValueError: Input 0 is incompatible with layer G_synthesis: expected shape=(None, 14, 512), found shape=(1, 18, 512)
```

**Comment by NTU-P04922004** [comment]
If I change to TF version 2.3.0, the error becomes a warning and the 256x256 data can still be generated.

```shell
WARNING:tensorflow:Model was constructed with shape (None, 14, 512) for input Tensor("G_synthesis/dlatents_in:0", shape=(None, 14, 512), dtype=float32), but it was called on an input with incompatible shape (None, 18, 512).
```

**Comment by YotamNitzan** [comment]
Hi @NTU-P04922004,
Thanks for bringing this bug to my attention. I see a shape mismatch but, weird enough, I don't encounter any error or warning with my TF 2.0 environment.

Anyway, I just pushed a new commit that I believe resolves this issue. Please confirm, as I wasn't able to reproduce the error.

**Comment by NTU-P04922004** [comment]
@YotamNitzan 

I have tested the updated code and the issue is resolved, thanks.
